version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - apt-get update && apt-get install -y jq
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=awsproject01 -Dsonar.organization=awsproject01 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=0a6069d5d0e188cf7ee87bad3bbdbfd7eeb1ae05 
      - sleep 10
      - |
        quality_status=$(curl -s -u $SONAR_TOKEN: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=awsproject01" \
          | jq -r '.projectStatus.status')
        echo "SonarCloud analysis status is $quality_status"
        if [ "$quality_status" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        fi
#Software Composition Analysis Scan (SCA scan) using Snyk

     - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=cf0a411e-c6b5-48c4-8760-6d89116b0162
          export SNYK_TOKEN
          mvn snyk:test -fn
